[package]
name = "cross-ping-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs.workspace = true
gbuiltin-eth-bridge.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
